name: Auto_Diamond_Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Build APK
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: stable
          python_version: 3.9
      - name: Upload APK
        run: |
          mv bin/*.apk ./app-release.apk
          git config --global user.name 'Diamond-Bot'
          git config --global user.email 'bot@diamond.x'
          git add app-release.apk
          git commit -m "New Auto-Server APK"
          git push
