name: Fixed_Build_V6
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # آزاد کردن فضای دیسک برای جلوگیری از ارور حافظه
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev python3-dev \
          libltdl-dev zlib1g-dev git zip unzip openjdk-17-jdk autoconf libtool pkg-config
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 virtualenv

      - name: Build APK with Debugger
        run: |
          # این دستور جلوی گیر کردن روی لایسنس را می‌گیرد
          yes | buildozer android debug
        continue-on-error: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Diamond-App-V6
          path: bin/*.apk
